GET http://localhost:3005/api/blogs


###
POST http://localhost:3005/api/blogs
content-type: application/json

{
    "title": "title2",
    "author":"ME",
    "url":"url2",
    "likes":"2"
}

###
DELETE http://localhost:3005/api/blogs/6316088085c5ff427ccf03f8